general =
{
  name = "RPi4 USB DAC";
};

alsa =
{
  output_device = "default";
  mixer_control_name = "none";
};

sessioncontrol =
{
  run_this_before_play_begins = "/etc/init.d/S55roonbridge stop";
};
